# Generated by Django 6.0.6 on 2026-06-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor'), ('admin', 'Administrador')], max_length=10)),
            ],
        ),
    ]
