/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectRoleRouteImport } from './routes/select-role'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfesorRouteImport } from './routes/profesor'
import { Route as AlumnoRouteImport } from './routes/alumno'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfesorIndexRouteImport } from './routes/profesor.index'
import { Route as AlumnoIndexRouteImport } from './routes/alumno.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProfesorSolicitudesRouteImport } from './routes/profesor.solicitudes'
import { Route as ProfesorMapaRouteImport } from './routes/profesor.mapa'
import { Route as ProfesorInventarioRouteImport } from './routes/profesor.inventario'
import { Route as ProfesorCalendarioRouteImport } from './routes/profesor.calendario'
import { Route as ProfesorAvisosRouteImport } from './routes/profesor.avisos'
import { Route as ProfesorAjustesRouteImport } from './routes/profesor.ajustes'
import { Route as AlumnoMapaRouteImport } from './routes/alumno.mapa'
import { Route as AlumnoCalendarioRouteImport } from './routes/alumno.calendario'
import { Route as AlumnoAjustesRouteImport } from './routes/alumno.ajustes'
import { Route as AdminSolicitudesRouteImport } from './routes/admin.solicitudes'
import { Route as AdminPersonasRouteImport } from './routes/admin.personas'
import { Route as AdminMapaRouteImport } from './routes/admin.mapa'
import { Route as AdminInventarioRouteImport } from './routes/admin.inventario'
import { Route as AdminCalendarioRouteImport } from './routes/admin.calendario'
import { Route as AdminAulasRouteImport } from './routes/admin.aulas'
import { Route as AdminAjustesRouteImport } from './routes/admin.ajustes'

const SelectRoleRoute = SelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesorRoute = ProfesorRouteImport.update({
  id: '/profesor',
  path: '/profesor',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumnoRoute = AlumnoRouteImport.update({
  id: '/alumno',
  path: '/alumno',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesorIndexRoute = ProfesorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfesorRoute,
} as any)
const AlumnoIndexRoute = AlumnoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlumnoRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfesorSolicitudesRoute = ProfesorSolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => ProfesorRoute,
} as any)
const ProfesorMapaRoute = ProfesorMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => ProfesorRoute,
} as any)
const ProfesorInventarioRoute = ProfesorInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => ProfesorRoute,
} as any)
const ProfesorCalendarioRoute = ProfesorCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => ProfesorRoute,
} as any)
const ProfesorAvisosRoute = ProfesorAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => ProfesorRoute,
} as any)
const ProfesorAjustesRoute = ProfesorAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => ProfesorRoute,
} as any)
const AlumnoMapaRoute = AlumnoMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AlumnoRoute,
} as any)
const AlumnoCalendarioRoute = AlumnoCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AlumnoRoute,
} as any)
const AlumnoAjustesRoute = AlumnoAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AlumnoRoute,
} as any)
const AdminSolicitudesRoute = AdminSolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPersonasRoute = AdminPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapaRoute = AdminMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventarioRoute = AdminInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarioRoute = AdminCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAulasRoute = AdminAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAjustesRoute = AdminAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alumno': typeof AlumnoRouteWithChildren
  '/profesor': typeof ProfesorRouteWithChildren
  '/register': typeof RegisterRoute
  '/select-role': typeof SelectRoleRoute
  '/admin/ajustes': typeof AdminAjustesRoute
  '/admin/aulas': typeof AdminAulasRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/mapa': typeof AdminMapaRoute
  '/admin/personas': typeof AdminPersonasRoute
  '/admin/solicitudes': typeof AdminSolicitudesRoute
  '/alumno/ajustes': typeof AlumnoAjustesRoute
  '/alumno/calendario': typeof AlumnoCalendarioRoute
  '/alumno/mapa': typeof AlumnoMapaRoute
  '/profesor/ajustes': typeof ProfesorAjustesRoute
  '/profesor/avisos': typeof ProfesorAvisosRoute
  '/profesor/calendario': typeof ProfesorCalendarioRoute
  '/profesor/inventario': typeof ProfesorInventarioRoute
  '/profesor/mapa': typeof ProfesorMapaRoute
  '/profesor/solicitudes': typeof ProfesorSolicitudesRoute
  '/admin/': typeof AdminIndexRoute
  '/alumno/': typeof AlumnoIndexRoute
  '/profesor/': typeof ProfesorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/select-role': typeof SelectRoleRoute
  '/admin/ajustes': typeof AdminAjustesRoute
  '/admin/aulas': typeof AdminAulasRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/mapa': typeof AdminMapaRoute
  '/admin/personas': typeof AdminPersonasRoute
  '/admin/solicitudes': typeof AdminSolicitudesRoute
  '/alumno/ajustes': typeof AlumnoAjustesRoute
  '/alumno/calendario': typeof AlumnoCalendarioRoute
  '/alumno/mapa': typeof AlumnoMapaRoute
  '/profesor/ajustes': typeof ProfesorAjustesRoute
  '/profesor/avisos': typeof ProfesorAvisosRoute
  '/profesor/calendario': typeof ProfesorCalendarioRoute
  '/profesor/inventario': typeof ProfesorInventarioRoute
  '/profesor/mapa': typeof ProfesorMapaRoute
  '/profesor/solicitudes': typeof ProfesorSolicitudesRoute
  '/admin': typeof AdminIndexRoute
  '/alumno': typeof AlumnoIndexRoute
  '/profesor': typeof ProfesorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alumno': typeof AlumnoRouteWithChildren
  '/profesor': typeof ProfesorRouteWithChildren
  '/register': typeof RegisterRoute
  '/select-role': typeof SelectRoleRoute
  '/admin/ajustes': typeof AdminAjustesRoute
  '/admin/aulas': typeof AdminAulasRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/mapa': typeof AdminMapaRoute
  '/admin/personas': typeof AdminPersonasRoute
  '/admin/solicitudes': typeof AdminSolicitudesRoute
  '/alumno/ajustes': typeof AlumnoAjustesRoute
  '/alumno/calendario': typeof AlumnoCalendarioRoute
  '/alumno/mapa': typeof AlumnoMapaRoute
  '/profesor/ajustes': typeof ProfesorAjustesRoute
  '/profesor/avisos': typeof ProfesorAvisosRoute
  '/profesor/calendario': typeof ProfesorCalendarioRoute
  '/profesor/inventario': typeof ProfesorInventarioRoute
  '/profesor/mapa': typeof ProfesorMapaRoute
  '/profesor/solicitudes': typeof ProfesorSolicitudesRoute
  '/admin/': typeof AdminIndexRoute
  '/alumno/': typeof AlumnoIndexRoute
  '/profesor/': typeof ProfesorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alumno'
    | '/profesor'
    | '/register'
    | '/select-role'
    | '/admin/ajustes'
    | '/admin/aulas'
    | '/admin/calendario'
    | '/admin/inventario'
    | '/admin/mapa'
    | '/admin/personas'
    | '/admin/solicitudes'
    | '/alumno/ajustes'
    | '/alumno/calendario'
    | '/alumno/mapa'
    | '/profesor/ajustes'
    | '/profesor/avisos'
    | '/profesor/calendario'
    | '/profesor/inventario'
    | '/profesor/mapa'
    | '/profesor/solicitudes'
    | '/admin/'
    | '/alumno/'
    | '/profesor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/select-role'
    | '/admin/ajustes'
    | '/admin/aulas'
    | '/admin/calendario'
    | '/admin/inventario'
    | '/admin/mapa'
    | '/admin/personas'
    | '/admin/solicitudes'
    | '/alumno/ajustes'
    | '/alumno/calendario'
    | '/alumno/mapa'
    | '/profesor/ajustes'
    | '/profesor/avisos'
    | '/profesor/calendario'
    | '/profesor/inventario'
    | '/profesor/mapa'
    | '/profesor/solicitudes'
    | '/admin'
    | '/alumno'
    | '/profesor'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alumno'
    | '/profesor'
    | '/register'
    | '/select-role'
    | '/admin/ajustes'
    | '/admin/aulas'
    | '/admin/calendario'
    | '/admin/inventario'
    | '/admin/mapa'
    | '/admin/personas'
    | '/admin/solicitudes'
    | '/alumno/ajustes'
    | '/alumno/calendario'
    | '/alumno/mapa'
    | '/profesor/ajustes'
    | '/profesor/avisos'
    | '/profesor/calendario'
    | '/profesor/inventario'
    | '/profesor/mapa'
    | '/profesor/solicitudes'
    | '/admin/'
    | '/alumno/'
    | '/profesor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlumnoRoute: typeof AlumnoRouteWithChildren
  ProfesorRoute: typeof ProfesorRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SelectRoleRoute: typeof SelectRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-role': {
      id: '/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof SelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesor': {
      id: '/profesor'
      path: '/profesor'
      fullPath: '/profesor'
      preLoaderRoute: typeof ProfesorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumno': {
      id: '/alumno'
      path: '/alumno'
      fullPath: '/alumno'
      preLoaderRoute: typeof AlumnoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesor/': {
      id: '/profesor/'
      path: '/'
      fullPath: '/profesor/'
      preLoaderRoute: typeof ProfesorIndexRouteImport
      parentRoute: typeof ProfesorRoute
    }
    '/alumno/': {
      id: '/alumno/'
      path: '/'
      fullPath: '/alumno/'
      preLoaderRoute: typeof AlumnoIndexRouteImport
      parentRoute: typeof AlumnoRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profesor/solicitudes': {
      id: '/profesor/solicitudes'
      path: '/solicitudes'
      fullPath: '/profesor/solicitudes'
      preLoaderRoute: typeof ProfesorSolicitudesRouteImport
      parentRoute: typeof ProfesorRoute
    }
    '/profesor/mapa': {
      id: '/profesor/mapa'
      path: '/mapa'
      fullPath: '/profesor/mapa'
      preLoaderRoute: typeof ProfesorMapaRouteImport
      parentRoute: typeof ProfesorRoute
    }
    '/profesor/inventario': {
      id: '/profesor/inventario'
      path: '/inventario'
      fullPath: '/profesor/inventario'
      preLoaderRoute: typeof ProfesorInventarioRouteImport
      parentRoute: typeof ProfesorRoute
    }
    '/profesor/calendario': {
      id: '/profesor/calendario'
      path: '/calendario'
      fullPath: '/profesor/calendario'
      preLoaderRoute: typeof ProfesorCalendarioRouteImport
      parentRoute: typeof ProfesorRoute
    }
    '/profesor/avisos': {
      id: '/profesor/avisos'
      path: '/avisos'
      fullPath: '/profesor/avisos'
      preLoaderRoute: typeof ProfesorAvisosRouteImport
      parentRoute: typeof ProfesorRoute
    }
    '/profesor/ajustes': {
      id: '/profesor/ajustes'
      path: '/ajustes'
      fullPath: '/profesor/ajustes'
      preLoaderRoute: typeof ProfesorAjustesRouteImport
      parentRoute: typeof ProfesorRoute
    }
    '/alumno/mapa': {
      id: '/alumno/mapa'
      path: '/mapa'
      fullPath: '/alumno/mapa'
      preLoaderRoute: typeof AlumnoMapaRouteImport
      parentRoute: typeof AlumnoRoute
    }
    '/alumno/calendario': {
      id: '/alumno/calendario'
      path: '/calendario'
      fullPath: '/alumno/calendario'
      preLoaderRoute: typeof AlumnoCalendarioRouteImport
      parentRoute: typeof AlumnoRoute
    }
    '/alumno/ajustes': {
      id: '/alumno/ajustes'
      path: '/ajustes'
      fullPath: '/alumno/ajustes'
      preLoaderRoute: typeof AlumnoAjustesRouteImport
      parentRoute: typeof AlumnoRoute
    }
    '/admin/solicitudes': {
      id: '/admin/solicitudes'
      path: '/solicitudes'
      fullPath: '/admin/solicitudes'
      preLoaderRoute: typeof AdminSolicitudesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/personas': {
      id: '/admin/personas'
      path: '/personas'
      fullPath: '/admin/personas'
      preLoaderRoute: typeof AdminPersonasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mapa': {
      id: '/admin/mapa'
      path: '/mapa'
      fullPath: '/admin/mapa'
      preLoaderRoute: typeof AdminMapaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventario': {
      id: '/admin/inventario'
      path: '/inventario'
      fullPath: '/admin/inventario'
      preLoaderRoute: typeof AdminInventarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendario': {
      id: '/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AdminCalendarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/aulas': {
      id: '/admin/aulas'
      path: '/aulas'
      fullPath: '/admin/aulas'
      preLoaderRoute: typeof AdminAulasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ajustes': {
      id: '/admin/ajustes'
      path: '/ajustes'
      fullPath: '/admin/ajustes'
      preLoaderRoute: typeof AdminAjustesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAjustesRoute: typeof AdminAjustesRoute
  AdminAulasRoute: typeof AdminAulasRoute
  AdminCalendarioRoute: typeof AdminCalendarioRoute
  AdminInventarioRoute: typeof AdminInventarioRoute
  AdminMapaRoute: typeof AdminMapaRoute
  AdminPersonasRoute: typeof AdminPersonasRoute
  AdminSolicitudesRoute: typeof AdminSolicitudesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAjustesRoute: AdminAjustesRoute,
  AdminAulasRoute: AdminAulasRoute,
  AdminCalendarioRoute: AdminCalendarioRoute,
  AdminInventarioRoute: AdminInventarioRoute,
  AdminMapaRoute: AdminMapaRoute,
  AdminPersonasRoute: AdminPersonasRoute,
  AdminSolicitudesRoute: AdminSolicitudesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AlumnoRouteChildren {
  AlumnoAjustesRoute: typeof AlumnoAjustesRoute
  AlumnoCalendarioRoute: typeof AlumnoCalendarioRoute
  AlumnoMapaRoute: typeof AlumnoMapaRoute
  AlumnoIndexRoute: typeof AlumnoIndexRoute
}

const AlumnoRouteChildren: AlumnoRouteChildren = {
  AlumnoAjustesRoute: AlumnoAjustesRoute,
  AlumnoCalendarioRoute: AlumnoCalendarioRoute,
  AlumnoMapaRoute: AlumnoMapaRoute,
  AlumnoIndexRoute: AlumnoIndexRoute,
}

const AlumnoRouteWithChildren =
  AlumnoRoute._addFileChildren(AlumnoRouteChildren)

interface ProfesorRouteChildren {
  ProfesorAjustesRoute: typeof ProfesorAjustesRoute
  ProfesorAvisosRoute: typeof ProfesorAvisosRoute
  ProfesorCalendarioRoute: typeof ProfesorCalendarioRoute
  ProfesorInventarioRoute: typeof ProfesorInventarioRoute
  ProfesorMapaRoute: typeof ProfesorMapaRoute
  ProfesorSolicitudesRoute: typeof ProfesorSolicitudesRoute
  ProfesorIndexRoute: typeof ProfesorIndexRoute
}

const ProfesorRouteChildren: ProfesorRouteChildren = {
  ProfesorAjustesRoute: ProfesorAjustesRoute,
  ProfesorAvisosRoute: ProfesorAvisosRoute,
  ProfesorCalendarioRoute: ProfesorCalendarioRoute,
  ProfesorInventarioRoute: ProfesorInventarioRoute,
  ProfesorMapaRoute: ProfesorMapaRoute,
  ProfesorSolicitudesRoute: ProfesorSolicitudesRoute,
  ProfesorIndexRoute: ProfesorIndexRoute,
}

const ProfesorRouteWithChildren = ProfesorRoute._addFileChildren(
  ProfesorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlumnoRoute: AlumnoRouteWithChildren,
  ProfesorRoute: ProfesorRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SelectRoleRoute: SelectRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
